# Generated by Django 5.1.3 on 2025-04-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_user', models.CharField(max_length=100)),
                ('apell_user', models.CharField(max_length=100)),
                ('email_user', models.EmailField(max_length=254)),
                ('contra_user', models.CharField(max_length=20)),
                ('cel_user', models.CharField(max_length=10)),
            ],
        ),
    ]
