# Generated by Django 5.1.3 on 2025-06-25 05:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carr', models.AutoField(primary_key=True, serialize=False)),
                ('fechacreac_carr', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('estado_carr', models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado')], default='activo', max_length=10)),
            ],
            options={
                'db_table': 'carrito',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cat', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_ord', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('cedula_ruc', models.CharField(max_length=13)),
                ('correo_cliente', models.EmailField(max_length=254)),
                ('direccion_cliente', models.CharField(max_length=255)),
                ('ciudad_cliente', models.CharField(max_length=100)),
                ('telefono_cliente', models.CharField(max_length=10)),
                ('direc_entre', models.TextField()),
                ('metodo_pago', models.CharField(max_length=100)),
                ('num_trans', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_trans', models.DateField(blank=True, null=True)),
                ('estado_ord', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('fechacrea_ord', models.DateField(auto_now_add=True)),
                ('fechactua_ord', models.DateField(auto_now=True)),
                ('carrito', models.ForeignKey(blank=True, db_column='id_carr', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ajditec.carrito')),
            ],
            options={
                'db_table': 'orden',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_prod', models.CharField(max_length=200)),
                ('descrip_prod', models.TextField()),
                ('img_prod', models.ImageField(upload_to='productos/')),
                ('borrado_prod', models.BooleanField(default=False)),
                ('fechcreac_prod', models.DateField(auto_now_add=True)),
                ('fechactu_prod', models.DateField(auto_now=True)),
                ('id_cat', models.ForeignKey(db_column='id_cat', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='Ajditec.categoria')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_mov', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(db_column='id_prod', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='Ajditec.producto')),
            ],
            options={
                'db_table': 'movimiento_inventario',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inve', models.AutoField(primary_key=True, serialize=False)),
                ('precunit_prod', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Stock Actual')),
                ('fechacrea_inve', models.DateField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fechactu_inve', models.DateField(auto_now=True, verbose_name='Fecha Actualización')),
                ('producto', models.OneToOneField(db_column='id_prod', on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='Ajditec.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id_detord', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('orden', models.ForeignKey(db_column='id_ord', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Ajditec.orden')),
                ('producto', models.ForeignKey(db_column='id_prod', on_delete=django.db.models.deletion.CASCADE, to='Ajditec.producto')),
            ],
            options={
                'db_table': 'detalle_orden',
            },
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id_detcarr', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(db_column='id_carr', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Ajditec.carrito')),
                ('producto', models.ForeignKey(db_column='id_prod', on_delete=django.db.models.deletion.CASCADE, to='Ajditec.producto')),
            ],
            options={
                'db_table': 'detalle_carrito',
            },
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id_regpag', models.AutoField(primary_key=True, serialize=False)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fech_crea', models.DateField(auto_now_add=True)),
                ('estado_reg', models.CharField(choices=[('Confirmado', 'Confirmado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Confirmado', max_length=20)),
                ('orden', models.ForeignKey(db_column='id_ord', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='Ajditec.orden')),
            ],
            options={
                'db_table': 'registro_pago',
            },
        ),
        migrations.CreateModel(
            name='DetalleTrans',
            fields=[
                ('id_detaltrans', models.AutoField(primary_key=True, serialize=False)),
                ('monto_trans', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banco_transfe', models.CharField(choices=[('Banco Produbanco', 'Banco Produbanco'), ('Banco Pichincha', 'Banco Pichincha')], default='Banco Pichincha', max_length=50)),
                ('codigo_compro', models.CharField(max_length=25, unique=True)),
                ('fecha_trans', models.DateField()),
                ('registro_pago', models.ForeignKey(db_column='id_regpag', on_delete=django.db.models.deletion.CASCADE, related_name='regispagos', to='Ajditec.registropago')),
            ],
            options={
                'db_table': 'detalle_trans',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], default='cliente', max_length=10)),
                ('cel_user', models.CharField(max_length=10, verbose_name='Celular')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='usuarios',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuarios',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
