# Generated by Django 5.1.3 on 2025-04-22 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_ord', models.AutoField(primary_key=True, serialize=False)),
                ('direc_entre', models.TextField()),
                ('metodo_pago', models.CharField(max_length=100)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_ord', models.BooleanField()),
                ('fechacrea_ord', models.DateField(auto_now_add=True)),
                ('fechactua_ord', models.DateField(auto_now=True)),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='Ajditec.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_prod', models.CharField(max_length=200)),
                ('descrip_prod', models.TextField()),
                ('img_prod', models.FileField(upload_to='productos')),
                ('esta_prod', models.CharField(choices=[('Agotado', 'Agotado'), ('Disponible', 'Disponible')], default='Agotado', max_length=20)),
                ('borrado_prod', models.BooleanField(default=False)),
                ('fechcreac_prod', models.DateField(auto_now_add=True)),
                ('fechactu_prod', models.DateField(auto_now=True)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='Ajditec.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inve', models.AutoField(primary_key=True, serialize=False)),
                ('precunit_prod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.IntegerField(default=0)),
                ('fechacrea_inve', models.DateField(auto_now_add=True)),
                ('fechactu_inve', models.DateField(auto_now=True)),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invetario', to='Ajditec.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id_detord', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('preciounitar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Ajditec.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ajditec.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carr', models.AutoField(primary_key=True, serialize=False)),
                ('prec_carr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_carr', models.IntegerField(default=1)),
                ('fechacreac_carr', models.DateTimeField(auto_now_add=True)),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='Ajditec.usuario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ajditec.producto')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id_regpag', models.AutoField(primary_key=True, serialize=False)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fech_crea', models.DateField(auto_now_add=True)),
                ('estado_reg', models.CharField(choices=[('Confirmado', 'Confirmado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Confirmado', max_length=20)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='Ajditec.orden')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTrans',
            fields=[
                ('id_detaltrans', models.AutoField(primary_key=True, serialize=False)),
                ('monto_trans', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banco_transfe', models.CharField(choices=[('Banco Produbanco', 'Banco Produbanco'), ('Banco Pichincha', 'Banco Pichincha')], default='Banco Pichincha', max_length=20)),
                ('codigo_compro', models.CharField(max_length=25)),
                ('comentario', models.TextField()),
                ('fecha_trans', models.DateField()),
                ('registro_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regispagos', to='Ajditec.registropago')),
            ],
        ),
    ]
