# Generated by Django 5.1.3 on 2025-05-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carrito',
            table='carrito',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='detallecarrito',
            table='detalle_Carrito',
        ),
        migrations.AlterModelTable(
            name='detalleorden',
            table='detalle_orden',
        ),
        migrations.AlterModelTable(
            name='detalletrans',
            table='detalle_trans',
        ),
        migrations.AlterModelTable(
            name='inventario',
            table='inventario',
        ),
        migrations.AlterModelTable(
            name='movimientoinventario',
            table='movimiento_inventario',
        ),
        migrations.AlterModelTable(
            name='orden',
            table='orden',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
        migrations.AlterModelTable(
            name='registropago',
            table='registro_pago',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
