# Generated by Django 5.1.3 on 2025-05-28 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fechacrea_inve',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fechactu_inve',
            field=models.DateField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='precunit_prod',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.OneToOneField(db_column='id_prod', on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='Ajditec.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock_actual',
            field=models.IntegerField(default=0, verbose_name='Stock Actual'),
        ),
    ]
