# Generated by Django 5.1.3 on 2025-07-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0002_notificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='id_notifi',
            new_name='id_noti',
        ),
    ]
