# Generated by Django 5.1.3 on 2025-05-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0002_alter_inventario_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='esta_prod',
        ),
    ]
