# Generated by Django 5.1.3 on 2025-07-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0003_rename_id_notifi_notificacion_id_noti'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='nom_banco',
            field=models.CharField(blank=True, choices=[('Banco Pichincha', 'Banco Pichincha'), ('Banco Produbanco', 'Banco Produbanco')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='DetalleTrans',
        ),
    ]
