# Generated by Django 5.1.3 on 2025-06-10 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0004_carrito_session_key'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detallecarrito',
            table='DetalleCarrito',
        ),
    ]
