# Generated by Django 5.1.3 on 2025-07-03 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0004_orden_nom_banco_delete_detalletrans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id_banco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=100, verbose_name='Nombre del Banco')),
                ('numero_cuenta', models.CharField(max_length=20, verbose_name='Número de Cuenta')),
                ('tipo_cuenta', models.CharField(choices=[('Ahorros', 'Ahorros'), ('Corriente', 'Corriente')], max_length=10, verbose_name='Tipo de Cuenta')),
                ('nombre_titular', models.CharField(max_length=150, verbose_name='Nombre del Titular')),
                ('identificacion_titular', models.CharField(max_length=13, verbose_name='Cédula o RUC del Titular')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'db_table': 'banco',
            },
        ),
        migrations.RemoveField(
            model_name='orden',
            name='nom_banco',
        ),
        migrations.AddField(
            model_name='orden',
            name='banco',
            field=models.ForeignKey(blank=True, db_column='id_banco', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ajditec.banco'),
        ),
    ]
