# Generated by Django 5.1.3 on 2025-06-10 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0005_alter_detallecarrito_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detallecarrito',
            table='detalle_carrito',
        ),
    ]
