# Generated by Django 5.1.3 on 2025-07-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0005_banco_remove_orden_nom_banco_orden_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='precio_uni',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
