# Generated by Django 5.1.3 on 2025-06-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0006_alter_detallecarrito_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='estado_carr',
            field=models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado')], default='activo', max_length=10),
        ),
    ]
