# Generated by Django 5.1.3 on 2025-07-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0006_movimientoinventario_precio_uni'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
