# Generated by Django 5.1.3 on 2025-07-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0007_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='precio_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
