# Generated by Django 5.1.3 on 2025-07-11 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0008_movimientoinventario_precio_anterior'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('direccion_prov', models.CharField(max_length=255, verbose_name='Dirección del Proveedor')),
                ('telefono_prov', models.CharField(max_length=20, verbose_name='Teléfono del Proveedor')),
                ('correo_prov', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('contacto_prov', models.CharField(max_length=150, verbose_name='Nombre de Contacto')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(db_column='id_prov', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='Ajditec.proveedor'),
        ),
    ]
