# Generated by Django 5.1.3 on 2025-07-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0010_impuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
