# Generated by Django 5.1.3 on 2025-07-12 06:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0011_orden_fecha_expira'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='iva_aplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='precio_aplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
