# Generated by Django 5.1.3 on 2025-07-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0012_detalleorden_iva_aplicado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='iva_aplicado',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='precio_aplicado',
        ),
        migrations.AddField(
            model_name='orden',
            name='metodo_entrega',
            field=models.CharField(choices=[('local', 'Local'), ('envio', 'Envío')], default='local', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_dios',
            field=models.BooleanField(default=False),
        ),
    ]
