# Generated by Django 5.1.3 on 2025-07-13 21:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0013_remove_detalleorden_iva_aplicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='iva_aplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='precio_aplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio Unitario'),
        ),
    ]
