# Generated by Django 5.1.3 on 2025-07-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0014_detalleorden_iva_aplicado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='iva_aplicado',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='precio_aplicado',
        ),
    ]
