# Generated by Django 5.1.3 on 2025-07-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ajditec', '0015_remove_detalleorden_iva_aplicado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='cedula_ruc',
        ),
        migrations.AddField(
            model_name='orden',
            name='numero_documento',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='tipo_documento',
            field=models.CharField(choices=[('cedula', 'Cédula'), ('ruc', 'RUC'), ('pasaporte', 'Pasaporte')], default='cedula', max_length=10),
        ),
    ]
